server:
  port: 8762
logging:
  level:
    com.xiaochong.core.mapper: DEBUG
spring:
  datasource:
    url: jdbc:mysql://dev.renrenhua.com:3306/wallet-core?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Rrh@2017
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
#druid参考官方配置
    initial-size: 1
    max-active: 20
    max-idle: 30
    min-idle: 5
    max-wait: 60000
#配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
#配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: false
    max-open-prepared-statements: 20
    max-pool-prepared-statement-per-connection-size: 20
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#配置监控统计拦截的filters
    filters: stat
#rabbitmq
  rabbitmq:
    host: dev.renrenhua.com
    virtualHost: myhost
    port: 5672
    username: rrh-myhost
    password: Rrh@2017
#redis
  redis:
    host: dev.renrenhua.com
    port: 6379
    password: Rrh@2017
    timeout: 3000
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
