server:
  port: 8079
spring:
#rabbitmq
  rabbitmq:
    host: localhost
#    virtualHost: /
    port: 5672
    username: admin
    password: admin
#redis
  redis:
    host: localhost
    port: 6379
    password: admin
    timeout: 3000
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1


